
spring:
  application:
    name: config
  profiles:
    active: native #for classpath
  cloud:
    config:
      server:
        native:
          search-locations:
            - "classpath:/config"

server:
  port: 8071