apiVersion: apps/v1
kind: Deployment
metadata:
    name: configserver-deployment
    labels:
        app: configserver-ms
spec:
    replicas: 1
    selector:
        matchLabels:
            app: configserver-ms
    template:
        metadata:
            labels:
                app: configserver-ms
        spec:
            containers:
                - name: configserver-ms
                  image: puscas/configserver:13
                  ports:
                      - containerPort: 8071

---

apiVersion: v1
kind: Service
metadata:
    name: configserver
spec:
    type: LoadBalancer
    selector:
        app: configserver-ms
    ports:
        - protocol: TCP
          port: 8071
          targetPort: 8071