server:
  port: 8090
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  profiles:
    active: "prod"
  application:
    name: loans

  datasource:
    url: jdbc:mysql://localhost:3307/loansdb
    username: root
    password: 'root'
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "configserver:http://configserver:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"