server:
  port: 8090
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  profiles:
    active: "prod"
  application:
    name: loans

  datasource:
    url: jdbc:mysql://localhost:3307/loansdb
    username: root
    password: 'root'
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "configserver:http://configserver:8071/"

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "cards"
    description: "easy bank cards application"
    version: "1.0.0"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true