apiVersion: v1
kind: ConfigMap
metadata:
    name: config-map
data:
  SPRING_PROFILES_ACTIVE: "prod,actuator,prometheus"
  SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka"
  CONFIGSERVER_APPLICATION_NAME: configserver
  EUREKA_APPLICATION_NAME: eurekaserver
  LOANS_APPLICATION_NAME: loans
  CARDS_APPLICATION_NAME: cards
  GATEAWAY_APPLICATION_NAME: gatewayserver
  KEYCLOACK_ADMIN: admin
  KEYCLOACK_ADMIN_PASSWORD: admin
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: root
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: "http://keycloak:7080/realms/master/protocol/openid-connect/certs"
  SPRING_RABBITMQ_HOST: "rabbit"

