spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:7080/realms/master/protocol/openid-connect/certs"
  application:
    name: "gatewayserver"
  config:
    import: "configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 10s
  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s
management:
  prometheus:
    metrics:
      export:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
info:
  app:
    name: "gatewayserver"
    description: "Eazy Bank Gateway Server Application"
    version: "1.0.0"

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
  level:
    com:
      puscas:
        gatewayserver: DEBUG

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 5
      permittedNumberOfCallsInHalfOpenState: 2
      failure-rate-threshold: 10
      automatic-transition-from-open-to-half-open-enabled: true
      minimum-number-of-calls: 2
      waitDurationInOpenState: 10000
  instances:
    accountsCircuitBreaker:
      slidingWindowSize: 5
      permittedNumberOfCallsInHalfOpenState: 2
      failure-rate-threshold: 10
      automatic-transition-from-open-to-half-open-enabled: true
      minimum-number-of-calls: 2
      waitDurationInOpenState: 10000

