services:
  accounts:
    image: puscassebi/accounts:s4
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: "300m"
          cpus: "0.5"
    networks:
      - puscassebi
  cards:
    image: puscassebi/cards
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: "300m"
          cpus: "0.5"
    networks:
      - puscassebi
  loans:
    image: puscassebi/loans:s4
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: "300m"
          cpus: "0.5"
    networks:
      - puscassebi

networks:
  puscassebi:
    driver: "bridge"