
server:
    port: 8070

spring:
  application:
    name: eurekaserver
  config:
    import: "configserver:http://localhost:8071/"

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      default: http://${eureka.instance.hostname}:${server.port}/eureka/