server:
  port: 9000
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
  profiles:
    active: "prod"
    name: "cards"

  datasource:
    url: jdbc:mysql://localhost:3308/cardsdb
    username: root
    password: 'root'
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "configserver:http://configserver:8071/"